import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Source_Sans_3 as SourceSans3 } from 'next/font/google';
import { auth } from '@clerk/nextjs/server';

import type { Metadata } from 'next';

import '@/app/globals.css';

const font = SourceSans3({
  subsets: ['latin'],
  variable: '--font-source-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <header className="h-[6rem] flex items-center justify-start bg-blue-200">
            <SignedOut>
              <div>{userId && <SignInButton />}</div>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
